metadata:
  hiddenPublish: false # Publish property set to embed.json
  pageTitle: Testing Page Title  # SEO Page Title
  description: Testing description # SEO Description
  ogTitle: Testing og title # OpenGraph Title used by Facebook
  ogDescription: Testing og description # OpenGraph Description Facebook
  ogType: article
  twitterCard: summary_large_image # https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
  twitterTitle: Testing twitter title
  twitterDescription: Testing twitter description
  overrideTwitterText: # When sharing via buttons, overrides the generated tweet and takes this field verbatim
  overrideEmailSubject: # When sharing via buttons, overrides the generated subject line and takes this field verbatim
  overrideEmailBody: # When sharing via buttons, overrides the generated body field and takes this field verbatim
  socialImage: https://nodeassets.nbcnews.com/cdnassets/projects/2017/10/deal-island/170625-Deal-Island-Brecher-09-840px.jpg # URL to Image assets ideally 1200x630
projectInitDate:
  year: '{{year}}'
  month: '{{month}}'
robotsDisallow: true # Allow robots from visit any page(s) on the site
dest: www # Metalsmith output directory
src: src # Metalsmith source directory
projectName: '{{projectName}}'
assetPath:
  domain: https://static-projects.nbcnews.com
  development: /
  stage: /
  production:
googleDocJson:
  fileId: null # Google Doc ID ex. 1bj563rIzGL95pvfWORPk-4ukUhRU-GYR55QGx9emyjY
  output: ./src/data/models/googledoc.json # Where the resulting JSON is saved via ./lib/googledocjson.js
dropboxPaperJson:
  fileId: null # Dropbox Paper ID ex. S7sSIlM2E0g6p3OXhhts4
  output: ./src/data/models/dropboxpaper.json # Where the resulting JSON is saved via ./lib/dropboxpaperjson.js
scripts: # Add external scripts globally ./partials/scripts.hbs
# - https://code.jquery.com/jquery-3.2.1.min.js
# - https://cdnjs.cloudflare.com/ajax/libs/video.js/5.20.1/video.min.js
collections: false # https://github.com/segmentio/metalsmith-collections
